### ISSUE TITLE
Navigation timeout of 2000 ms exceeded

### ISSUE THREAD

**Issue by vcomplyRahul** [typpo/google-charts-node#5]
When i use google-charts-node in my backend then it gives "**Navigation timeout of 2000 ms exceeded**" most of the Time. and log is ..
{ TimeoutError: Navigation timeout of 2000 ms exceeded
    at Promise.then (C:\angular\b-all\node_modules\google-charts-node\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111)
  -- ASYNC --
    at Frame.<anonymous> (C:\angular\b-all\node_modules\google-charts-node\node_modules\puppeteer\lib\helper.js:116:19)
    at Page.setContent (C:\angular\b-all\node_modules\google-charts-node\node_modules\puppeteer\lib\Page.js:550:46)
    at Page.<anonymous> (C:\angular\b-all\node_modules\google-charts-node\node_modules\puppeteer\lib\helper.js:117:27)
    at Object.renderGoogleChart [as render] (C:\angular\b-all\node_modules\google-charts-node\lib\render.js:32:16)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

**Comment by typpo** [comment]
Hi @vcomplyRahul, thanks for the report.  There is a default 2 second timeout for rendering.  If you upgrade to v1.0.3 (just released), the timeout is increased to 5 seconds (5000 ms) and you can override it by setting the `GOOGLE_CHARTS_RENDER_TIMEOUT_MS` environmental variable.

For example:
```
export GOOGLE_CHARTS_RENDER_TIMEOUT_MS=10000
./run_my_app
```

**Comment by vcomplyRahul** [comment]
working fine.
Thanks @typpo
